name: Release

on:
    push:
        tags:
            - "*"
jobs:
    build:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            USERNAME: ${{ github.actor }}
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPOSITORY: ${{ github.repository }}
        steps:
            -   name: Check out
                uses: actions/checkout@v5
            -   name: Set up JDK
                uses: actions/setup-java@v5.0.0
                with:
                    distribution: "adopt"
                    java-version: "21"
            -   name: Create empty required files
                run: |
                    touch ./local.properties
                    touch ./github.properties
            -   name: Build & Publish
                run: |
                    chmod +x publish.sh
                    ./publish.sh
