name: Unit Test

on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        name: Unit Test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            -   name: Fetch Sources
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: actions/setup-java@v4.6.0
                with:
                    distribution: "adopt"
                    java-version: "21"

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Run unit test and collect coverage
                run: ./gradlew jvmTest :koverLog

            -   name: Create comment file
                run: |
                    echo "# Test Coverage" > comment.txt
                    cat "build/kover/coverage.txt" >> comment.txt

            -   name: Post PR comment
                uses: marocchino/sticky-pull-request-comment@v2
                with:
                    recreate: true
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    path: comment.txt
